GraphingLib/GraphingLibStyleEditor

gl-style-editor/main.py

Closes issue #1. There is still the issue that the default color while opening the app is the default rc params, not the chosen style (graphinglib styles) rc params.

Improved color picker

---

gl-style-editor/main.py
pyproject.toml

Added better colour picker, tab reorganization, save functionality, and GL params compatibility.

1 feature request better color picker

---

gl-style-editor/main.py

Added all options in Curve tab and made it scrollable. Closes #6

6 options in curve tab

---

gl-style-editor/__init__.py
gl-style-editor/figure_tab.py
gl-style-editor/fits_tab.py
gl-style-editor/glse.py
gl-style-editor/other_gl_tab.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/plotting_2d_tab.py
gl-style-editor/shapes_tab.py
gl-style-editor/widgets.py
pyproject.toml

New organization :
create_<module>_tab functions moved into <module>_tab.py files
custom widgets have been moved into widgets.py

9 code reorganization

---

gl-style-editor/figure_tab.py
gl-style-editor/glse.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/widgets.py

Changed the figure tab's widgets for the custom ones. Closes #11

11 cant modify sliders value in figure tab

---

gl-style-editor/glse.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/widgets.py

Added all widgets for scatter tab. Closes #14

Completed scatter tab

---

gl-style-editor/glse.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/widgets.py

See last comment in #15 . Closes #15

15 complete histogram tab

---

gl-style-editor/glse.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/shapes_tab.py
gl-style-editor/widgets.py

Filled in both Circle and Rectangle tabs
#24

24 fill in circle tab

---

gl-style-editor/custom.css
gl-style-editor/glse.py
gl-style-editor/shapes_tab.py
gl-style-editor/widgets.py
pyproject.toml

Changed the theme to the qt-material theme and ajusted some widgets.

Chaged theme to qt-material

---

gl-style-editor/glse.py

Improved default style behaviour

---

gl-style-editor/glse.py
gl-style-editor/widgets.py

Added indicators to style manager

---

.gitignore
gl-style-editor/figures/contour.py
gl-style-editor/figures/curve.py
gl-style-editor/figures/heatmap.py
gl-style-editor/figures/histogram.py
gl-style-editor/figures/scatter.py
gl-style-editor/figures/stream.py
gl-style-editor/figures/vectorfield.py
gl-style-editor/fits_tab.py
gl-style-editor/glse.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/plotting_2d_tab.py
gl-style-editor/widgets.py

18 multiple graphinglib example plots with different plot types

---

gl-style-editor/figure_tab.py
gl-style-editor/other_gl_tab.py
gl-style-editor/plotting_1d_tab.py
gl-style-editor/plotting_2d_tab.py
gl-style-editor/shapes_tab.py

Changed properties to dashes

---

glse/figures/line.py
glse/shapes_tab.py

Added Line tab content and example

---

glse/glse.py

Fixed double figure execution when creating new style

---

glse/other_gl_tab.py
glse/plotting_1d_tab.py

Fix bug where exotic markers weren't supported (horrible)

---

glse/figures/fits.py
glse/fits_tab.py
glse/glse.py
glse/plotting_2d_tab.py
glse/widgets.py

Also added mechanism to use a single widget to control a parameter for multiple objects at once.
Closes issue #37.

Filled in fits tab

---

glse/plotting_2d_tab.py

Closes issue #23.
Filled in VectorField tab.

Filled in vectorfield tab

---

glse/figures/polygon.py
glse/shapes_tab.py

Filled polygon tab.
Closes issue #75.
- [ N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting-a-pull-request).

Filled polygon tab

---

glse/figures/histogram.py
glse/plotting_1d_tab.py

Closes issue #66. All histogram widgets are now linked and they affect the figure.

All histogram widgets now functional

---

glse/glse.py

Added save figure button which prompts user to select file type (png, pdf, or svg), figure size in inches, and dpi.

Added save figure functionality

---

glse/figures/curve.py
glse/figures/figure.py
glse/figures/heatmap.py
glse/figures/hlines and vlines.py
glse/figures/point.py
glse/figures/polygon.py
glse/figures/scatter.py
glse/figures/table.py
glse/figures/text.py
glse/glse.py
glse/plotting_1d_tab.py

Added examples and improved existing ones.
Closes issue #70.

70 feature request add figure examples for each tab improve existing ones

---

glse/plotting_1d_tab.py

Added error curve parameters to curve tab.

Added error curves to Curve tab

---

glse/glse.py

See title, self explanatory.
Closes issue #93.

Fixed bug where figure opened in duplicate when opening a style

---

glse/figure_tab.py

Added more customization to figures that were already in the rc params like legend colours, tick directions, grid opacity, font family and size, etc.
Closes issue #87.
- [N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting-a-pull-r …

Added more customization options in figure tab

---

README.md

Added content to README.md

---

glse/figure_tab.py
glse/glse.py
glse/widgets.py

Added table of rc params for user to add custom params that aren't currently handled in GLSE's other widgets.
Closes issue #88.

88 feature request possibility to add custom rc params

---

docs/index.rst
glse/plotting_2d_tab.py

Added description of how to open GLSE from a python script in documentation homepage/quickstart.
Closes issue #100.

100 documentation add glse.run description

---

docs/index.rst

Added button pointing to handbook on homepage/quickstart.
Closes issue #99.

Added button pointing to handbook on homepage

---

glse/glse.py

Fixed GUI style to change the QLineEdit text color to white and did a small rework of the example figure selection section. Closes #73 
- [N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting-a-pull-r …

Fixed QLineEdit text color in style file

---

glse/figures/table.py
glse/other_gl_tab.py

Added new Table customization widgets: cell colors, column colors, row colors, edge color, edge width, and text color.
Closes issue #105.
- [N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting-a-pull …

Added new Table customization widgets

---

docs/index.rst

112 documentation improve image size scaling with screen width

---

glse/figure_tab.py
glse/fits_tab.py
glse/other_gl_tab.py
glse/plotting_1d_tab.py
glse/plotting_2d_tab.py
glse/widgets.py

Added dpi param to figure tab and added line edit to sliders so user can see/edit actual values.
Closes issue #117.

117 feature request implement new dpi parameter in figure tab

---

glse/other_gl_tab.py

Added color picker for text color. Also, linked point face and edge colors so that they can't both be None at the same time.
Closes issue #118.
- [N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guideline-for-submitting- …

Added color picker for text color

---

glse/figure_tab.py
glse/widgets.py

Added new TupleWidget and used it for Figure and MultiFigure sizes. MultiFigure params are now all handled by GUI (there is only size for now).
Closes issue #122.
- [N/A] If your changes modify the UI or add/change functionality, a short release note has been added to the ``docs/release_notes/upcoming_changes`` directory following the [Guidelines for submitting a pull request](https://www.graphinglib.org/en/latest/contributing.html#guidel …

Add TupleWidget for figure size

---

docs/index.rst

Added image pre loading to fix bug with fade transitions
- [N/A] Links to the related issue (#....)

Added pre-loading for images in home page

---

glse/glse.py

Closes issue #127. Made css file path relative to current file so it can be found anywhere.

Update CSS file path in glse.py
